# Generated by Django 3.2.15 on 2022-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
