# Generated by Django 3.2.15 on 2022-08-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0003_alter_registeruser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
