# Generated by Django 3.2.15 on 2022-08-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0004_auto_20220816_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
